apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-crud-app
  template:
    metadata:
      labels:
        app: springboot-crud-app
    spec:
      containers:
      - name: springboot-crud-app
        image: sanoj619/crud-product:latest
        ports:
        - containerPort: 8082
        env:
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m"
