apiVersion: v1
kind: Service
metadata:
  name: springboot-crud-app-service
spec:
  selector:
    app: springboot-crud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer
